# For more information: https://laravel.com/docs/sail
version: '3.3'
services:
    nginx:
        container_name: nginx
        image: atemndobs/nginx:v1
#        build:
#            context: ./docker/nginx
        depends_on:
            -   php-fpm
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - "./docker/logs/nginx:/var/log/nginx"
            - "./docker/nginx/sites:/etc/nginx/sites-available"
            - "./docker/nginx/ssl:/etc/nginx/ssl"
            - "./:/var/www/html/:default"
        networks:
            - sail
    php-fpm:
        container_name: php-fpm
        image: atemndobs/php-fpm:8.1
#        build:
#            context: ./docker/php-fpm
        volumes:
            - "./:/var/www/html/:default"
            - "./scdl.cfg:/root/.config/scdl/scdl.cfg"
        networks:
            - sail
        expose:
            -   9000
        depends_on:
            - mysql
            - redis
            - meilisearch
    mysql:
        container_name: mysql
        image: 'mysql/mysql-server:8.0'
        #restart: always
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - '3306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: 'mage'
            MYSQL_ROOT_HOST: "mysql"
            MYSQL_DATABASE: 'mage'
            MYSQL_USER: 'mage'
            MYSQL_PASSWORD: 'mage'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - sail-mysql:/var/lib/mysql
        networks:
            - sail
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
            retries: 3
            timeout: 5s

    meilisearch:
        container_name: meilisearch
        image: 'getmeili/meilisearch:latest'
        ports:
            - '7700:7700'
        volumes:
            - 'sail-meilisearch:/data.ms'
        networks:
            - sail
        healthcheck:
            test: ["CMD", "wget", "--no-verbose", "--spider",  "http://localhost:7700/health"]
            retries: 3
            timeout: 5s
    rabbitmq:
        image: rabbitmq:3-management-alpine
        container_name: 'rabbitmq'
        ports:
            - "5672:5672"
            - "15672:15672"
        volumes:
            - 'sail-rabbitmq:/data.rabbitmq'
        networks:
            - sail

    redis:
        container_name: redis
        image: 'redis:alpine'
        ports:
            - '6380:6379'
        volumes:
            - 'sail-redis:/data'
        networks:
            - sail
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            retries: 3
            timeout: 5s

    mailhog:
        container_name: mailhog
        image: mailhog/mailhog:latest
        ports:
            - '1025:1025'
            - '8025:8025'
        networks:
            - sail
networks:
    sail:
        driver: bridge

volumes:
    sail-mysql:
        driver: local
    sail-redis:
        driver: local
    sail-meilisearch:
        driver: local
    sail-rabbitmq:
        driver: local
