# create mysql pod from docker-compose.yaml
apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  labels:
    name: mysql-pod
    app: curator-app
spec:
  containers:
    - name: mysql
      image: mysql/mysql-server:8.0
      command:
      - --default-authentication-plugin=mysql_native_password
      ports:
        - containerPort: 3306
          hostPort: 3307
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: mage
        - name: MYSQL_ROOT_HOST
          value: mysql
        - name: MYSQL_DATABASE
          value: mage
        - name: MYSQL_USER
          value: mage
        - name: MYSQL_PASSWORD
          value: mage
        - name: MYSQL_ALLOW_EMPTY_PASSWORD
          value: 1
      volumeMounts:
        - name: sail-mysql
          mountPath: /var/lib/mysql
      resources:
        requests:
          cpu: 100m
          memory: 100Mi
        limits:
          cpu: 100m
          memory: 100Mi
      livenessProbe:
        httpGet:
          path: /healthcheck
          port: 3306
        initialDelaySeconds: 30
        periodSeconds: 10
        failureThreshold: 3
        successThreshold: 1
        timeoutSeconds: 1
