apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: strapi
  name: strapi
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: strapi
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f docker-compose.yml convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.network/sail: "true"
        io.kompose.service: strapi
    spec:
      containers:
        - env:
            - name: DATABASE_CLIENT
              value: mysql
            - name: DATABASE_HOST
              value: mysql
            - name: DATABASE_NAME
              value: mage
            - name: DATABASE_PASSWORD
              value: mage
            - name: DATABASE_PORT
              value: "3306"
            - name: DATABASE_USERNAME
              value: mage
          image: atemndobs/strapi:1.0
          name: strapi
          ports:
            - containerPort: 1337
          resources: {}
          volumeMounts:
            - mountPath: /srv/app
              name: strapi-claim0
      restartPolicy: Always
      volumes:
        - name: strapi-claim0
          persistentVolumeClaim:
            claimName: strapi-claim0
status: {}
