version: '3.7'
services:
    laravel.test:
        build:
            context: ./docker/8.1
            dockerfile: Dockerfile
            args:
                WWWGROUP: 1000
                WWWUSER: "sail"
        image: sail-8.1/app
        ports:
            - 8899:80
            - 6001:6001
        environment:
            WWWUSER: sail
            LARAVEL_SAIL: 1
        volumes:
            - './:/var/www/html'
            - './scdl.cfg:/root/.config/scdl/scdl.cfg'
        networks:
            - sail
        depends_on:
            - mysql
            - redis
            - meilisearch
            - rabbitmq
            - strapi
            - mailhog
    strapi:
        container_name: strapi
        image: atemndobs/strapi:1.0
        environment:
            DATABASE_CLIENT: mysql
            DATABASE_HOST: mysql
            DATABASE_PORT: 3306
            DATABASE_NAME: mage
            DATABASE_USERNAME: mage
            DATABASE_PASSWORD: mage
        ports:
            - 1337:1337
        volumes:
            - ./../strapi:/srv/app
        depends_on:
            - mysql
        networks:
            - sail
    mysql:
        image: 'mysql/mysql-server:8.0'
        #restart: always
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - '3307:3306'
        environment:
            MYSQL_ROOT_PASSWORD: 'mage'
            MYSQL_ROOT_HOST: "mysql"
            MYSQL_DATABASE: 'mage'
            MYSQL_USER: 'mage'
            MYSQL_PASSWORD: 'mage'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - sail-mysql:/var/lib/mysql
        networks:
            - sail
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-pmage}"]
            retries: 3
            timeout: 5s

    meilisearch:
        image: 'getmeili/meilisearch:latest'
        ports:
            - '7700:7700'
        volumes:
            - 'sail-meilisearch:/data.ms'
        networks:
            - sail
        healthcheck:
            test: ["CMD", "wget", "--no-verbose", "--spider",  "http://localhost:7700/health"]
            retries: 3
            timeout: 5s
    rabbitmq:
        image: rabbitmq:3-management-alpine
        container_name: 'rabbitmq'
        ports:
            - 5672:5672
            - 15672:15672
        volumes:
            - 'sail-rabbitmq:/data.rabbitmq'
        networks:
            - sail

    redis:
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6380}:6379'
        volumes:
            - 'sail-redis:/data'
        networks:
            - sail
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            retries: 3
            timeout: 5s

    mailhog:
        image: 'mailhog/mailhog:latest'
        ports:
            - '1025:1025'
            - '8025:8025'
        networks:
            - sail
networks:
    sail:
        driver: bridge

volumes:
    sail-mysql:
        driver: local
    sail-redis:
        driver: local
    sail-meilisearch:
        driver: local
    sail-rabbitmq:
        driver: local
