apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nginx
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.network/sail: "true"
        io.kompose.service: nginx
    spec:
      containers:
        - image: atemndobs/nginx:v1
          name: nginx
          ports:
            - containerPort: 80
            - containerPort: 443
          resources: {}
          volumeMounts:
            - mountPath: /var/log/nginx
              name: nginx-claim0
            - mountPath: /etc/nginx/sites-available
              name: nginx-claim1
            - mountPath: /etc/nginx/ssl
              name: nginx-claim2
#            - mountPath: /var/www/html/
#              name: nginx-claim3
            - mountPath: /var/www/html/
              name: nginx
      restartPolicy: Always
      volumes:
        - name: nginx-claim0
          persistentVolumeClaim:
            claimName: nginx-claim0
        - name: nginx-claim1
          persistentVolumeClaim:
            claimName: nginx-claim1
        - name: nginx-claim2
          persistentVolumeClaim:
            claimName: nginx-claim2
#        - name: nginx-claim3
#          persistentVolumeClaim:
#            claimName: nginx-claim3
        - name: nginx
          hostPath:
            path: /home/atem/sites/curator/laravel/
            type: Directory
status: {}
