FROM php:8.1-cli-alpine
MAINTAINER Shift <support@laravelshift.com>

RUN apk update && apk upgrade && apk add --no-cache icu-dev git git-lfs grep openssh patch rsync sqlite nodejs npm
RUN docker-php-ext-install -j$(nproc) intl

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/bin --filename=composer
RUN composer global require -n -o -q "squizlabs/php_codesniffer:~3.7.0" "friendsofphp/php-cs-fixer:~3.8.0" "rector/rector:0.13.5"
ENV PATH "$PATH:/root/.composer/vendor/bin"

RUN npm install -g prettier prettier-plugin-tailwindcss

#RUN wget -qO /run/loader.sh https://laravelshift.com/api/docker


#RUN /run/loader.sh
ENTRYPOINT ["sh", "/run/loader.sh"]
